// Auto-generated by a2r transpiler

use std::boxed::Box;
use autoterm_core::{PtySession, Damage, StyledChar};
use autoterm_core::term::Color;
#[allow(dead_code)]
struct EngineFace {
    pub inner: PtySession,
    pub snapshot: Vec<Vec<StyledChar>>,
}

fn kind_color_auto(c: Color) -> u32 {
    match c {
        Color::Named(n) => return 16777216 + (n as u32),
        Color::Indexed(i) => return 16777216 + (i as u32),
        Color::Spec(rgb) => return 33554432 + (rgb.r as u32) * 65536 + (rgb.g as u32) * 256 + (rgb.b as u32),
    };
    return 0;
}

fn default_cols(cols: i64) -> usize {
    if cols <= 0 {
        return 80 as usize;
    }
    return (cols as usize);
}

fn default_rows(rows: i64) -> usize {
    if rows <= 0 {
        return 24 as usize;
    }
    return (rows as usize);
}

/// Plan 610 ⑤: pointer bridge kit — raw-buffer/out-param access from #[export]
/// bodies is confined here (004 §3.5: unsafe lives in generated code only;
/// Auto bodies stay safe). All writes are null-tolerant no-ops.
mod auto_cabi_kit {
    /// Null pointer of the statically expected pointee type (spawn-failure paths).
    pub fn cabi_null<T>() -> *mut T {
        std::ptr::null_mut()
    }

    /// Default shell name (COMSPEC → fallback "cmd"), mirroring engine ffi.rs.
    pub fn cabi_default_shell() -> String {
        std::env::var("COMSPEC").unwrap_or_else(|_| "cmd".to_owned())
    }

    /// Copy UTF-8 bytes of `s` + NUL into `p` (≤cap). Returns total bytes incl.
    /// NUL (truncation mirrors the engine row_text contract); null p is a
    /// length-only probe.
    pub fn cabi_copy_cstr(p: *mut u8, cap: i64, s: &str) -> i64 {
        if p.is_null() || cap <= 0 {
            return (s.len() + 1) as i64;
        }
        let bytes = s.as_bytes();
        let n = bytes.len().min(cap as usize - 1);
        unsafe {
            let mut out = std::slice::from_raw_parts_mut(p, n + 1);
            out[..n].copy_from_slice(&bytes[..n]);
            out[n] = 0;
        }
        (bytes.len() + 1) as i64
    }

    /// Write one u32 element at `idx` (C `unsigned int`/`int` out-params — the
    /// engine face models non-negative int outs as u32, bit-compatible).
    pub fn cabi_write_u32(p: *mut u32, idx: i64, v: u32) {
        if p.is_null() {
            return;
        }
        unsafe { *p.add(idx as usize) = v; }
    }

    /// Write one u8 element at `idx` (byte buffers).
    pub fn cabi_write_u8(p: *mut u8, idx: i64, v: u8) {
        if p.is_null() {
            return;
        }
        unsafe { *p.add(idx as usize) = v; }
    }

    /// Copy `len` bytes from a raw const buffer into an owned Vec (host→child
    /// input path); null/empty buffer → empty Vec.
    pub fn cabi_bytes_vec(p: *const u8, len: i64) -> Vec<u8> {
        if p.is_null() || len <= 0 {
            return Vec::new();
        }
        unsafe { std::slice::from_raw_parts(p, len as usize).to_vec() }
    }

    /// Reclaim a boxed value through its raw handle (free paths); null no-op.
    pub fn cabi_drop_boxed<T>(p: *mut T) {
        if p.is_null() {
            return;
        }
        drop(unsafe { Box::from_raw(p) });
    }

    /// Bridge for `Option<(usize, usize)>` payloads (cursor): Some → write both
    /// u32 slots, return 1; None → 0. Auto has no tuple face, so foreign
    /// option-tuple values cross through this kit helper untouched.
    pub fn cabi_write_opt_tuple2_u32(cur: Option<(usize, usize)>, p0: *mut u32, p1: *mut u32) -> i64 {
        match cur {
            Some((a, b)) => {
                cabi_write_u32(p0, 0, a as u32);
                cabi_write_u32(p1, 0, b as u32);
                1
            }
            None => 0,
        }
    }
}
pub use auto_cabi_kit::*;
/// Plan 610 ⑤: C ABI export face for `autoterm_engine_spawn` — the sibling wrapper bridges C widths
/// to the safe body below; the exported symbol equals the fn name (no_mangle
/// ignores the module path).
mod autoterm_engine_spawn_c_export {
    use super::*;
    #[unsafe(no_mangle)]
    pub extern "C" fn autoterm_engine_spawn(cols: i32, rows: i32, program: *const std::os::raw::c_char) -> *mut EngineFace {
        let program_conv: String = if program.is_null() { String::new() } else { unsafe { std::ffi::CStr::from_ptr(program) }.to_string_lossy().into_owned() };
        super::autoterm_engine_spawn(cols as i64, rows as i64, &program_conv)
    }
}
fn autoterm_engine_spawn(cols: i64, rows: i64, program: &str) -> *mut EngineFace {
    let mut prog: String = program.to_string();
    if prog == "" {
        prog = cabi_default_shell();
    }
    let mut args: Vec<String> = vec![];
    let r = PtySession::spawn(prog.as_str(), args, default_cols(cols), default_rows(rows));
    match r {
        Ok(session) => {
            let boxed = Box::new(EngineFace { inner: session, snapshot: vec![] });
            return Box::into_raw(boxed);
        },
        Err(e) => return cabi_null(),
    };
    return cabi_null();
}

/// Plan 610 ⑤: C ABI export face for `autoterm_engine_write_input` — the sibling wrapper bridges C widths
/// to the safe body below; the exported symbol equals the fn name (no_mangle
/// ignores the module path).
mod autoterm_engine_write_input_c_export {
    use super::*;
    #[unsafe(no_mangle)]
    pub extern "C" fn autoterm_engine_write_input(h: *mut EngineFace, bytes: *mut u8, len: usize) {
        match unsafe { h.as_mut() } { Some(h) => super::autoterm_engine_write_input(h, bytes, len), None => () }
    }
}
fn autoterm_engine_write_input(h: &mut EngineFace, bytes: *mut u8, len: usize) {
    let v = cabi_bytes_vec(bytes, (len as i64));
    h.inner.write_input(v.as_slice());
}

/// Plan 610 ⑤: C ABI export face for `autoterm_engine_feed_ready` — the sibling wrapper bridges C widths
/// to the safe body below; the exported symbol equals the fn name (no_mangle
/// ignores the module path).
mod autoterm_engine_feed_ready_c_export {
    use super::*;
    #[unsafe(no_mangle)]
    pub extern "C" fn autoterm_engine_feed_ready(h: *mut EngineFace) -> i32 {
        match unsafe { h.as_mut() } { Some(h) => super::autoterm_engine_feed_ready(h) as i32, None => -1 }
    }
}
fn autoterm_engine_feed_ready(h: &mut EngineFace) -> i64 {
    if h.inner.drain() {
        return 1;
    }
    return 0;
}

/// Plan 610 ⑤: C ABI export face for `autoterm_engine_take_dirty_rows` — the sibling wrapper bridges C widths
/// to the safe body below; the exported symbol equals the fn name (no_mangle
/// ignores the module path).
mod autoterm_engine_take_dirty_rows_c_export {
    use super::*;
    #[unsafe(no_mangle)]
    pub extern "C" fn autoterm_engine_take_dirty_rows(h: *mut EngineFace, out_rows: *mut u32, cap: i32) -> i32 {
        match unsafe { h.as_mut() } { Some(h) => super::autoterm_engine_take_dirty_rows(h, out_rows, cap as i64) as i32, None => -1 }
    }
}
fn autoterm_engine_take_dirty_rows(mut h: &mut EngineFace, out_rows: *mut u32, cap: i64) -> i64 {
    let damage = h.inner.term.take_damage();
    h.snapshot = h.inner.term.visible_styled_lines();
    match damage {
        Damage::Full => return -1,
        Damage::Lines(lines) => {
            if lines.is_empty() {
                return 0;
            }
            let rows_count: i64 = ((h.snapshot.len() as i64) as i64);
            let lim: i64 = if cap < rows_count {
                cap
            } else {
                rows_count
            };
            let count: i64 = ((lines.len() as i64) as i64);
            let n: i64 = if count < lim {
                count
            } else {
                lim
            };
            let mut i: i64 = 0;
            while i < n {
                cabi_write_u32(out_rows, i, (lines[(i) as usize].clone() as u32));
                i = i + 1;
            }
            return n;
        },
    };
    return 0;
}

/// Plan 610 ⑤: C ABI export face for `autoterm_engine_row_text` — the sibling wrapper bridges C widths
/// to the safe body below; the exported symbol equals the fn name (no_mangle
/// ignores the module path).
mod autoterm_engine_row_text_c_export {
    use super::*;
    #[unsafe(no_mangle)]
    pub extern "C" fn autoterm_engine_row_text(h: *mut EngineFace, row: i32, out_buf: *mut u8, cap: i32) -> i32 {
        match unsafe { h.as_mut() } { Some(h) => super::autoterm_engine_row_text(h, row as i64, out_buf, cap as i64) as i32, None => -1 }
    }
}
fn autoterm_engine_row_text(h: &mut EngineFace, row: i64, out_buf: *mut u8, cap: i64) -> i64 {
    if row < 0 || row >= ((h.snapshot.len() as i64) as i64) {
        return -1;
    }
    let mut s: String = "".to_string();
    let mut i: i64 = 0;
    let n = (h.snapshot[((row as usize)) as usize].clone().len() as i64);
    while i < (n as i64) {
        let sc = h.snapshot[((row as usize)) as usize].clone()[(i) as usize].clone();
        s.push(sc.c);
        i = i + 1;
    }
    return (cabi_copy_cstr(out_buf, cap, s.as_str()) as i64);
}

/// Plan 610 ⑤: C ABI export face for `autoterm_engine_row_style` — the sibling wrapper bridges C widths
/// to the safe body below; the exported symbol equals the fn name (no_mangle
/// ignores the module path).
mod autoterm_engine_row_style_c_export {
    use super::*;
    #[unsafe(no_mangle)]
    pub extern "C" fn autoterm_engine_row_style(h: *mut EngineFace, row: i32, out: *mut u32, cap: i32) -> i32 {
        match unsafe { h.as_mut() } { Some(h) => super::autoterm_engine_row_style(h, row as i64, out, cap as i64) as i32, None => -1 }
    }
}
fn autoterm_engine_row_style(h: &mut EngineFace, row: i64, out: *mut u32, cap: i64) -> i64 {
    if row < 0 || row >= ((h.snapshot.len() as i64) as i64) {
        return -1;
    }
    let n = (h.snapshot[((row as usize)) as usize].clone().len() as i64);
    let need: i64 = (n as i64) * 2;
    if cap < need {
        return -1;
    }
    let mut i: i64 = 0;
    while i < (n as i64) {
        let sc = h.snapshot[((row as usize)) as usize].clone()[(i) as usize].clone();
        cabi_write_u32(out, i * 2, kind_color_auto(sc.fg.clone()));
        cabi_write_u32(out, i * 2 + 1, kind_color_auto(sc.bg.clone()));
        i = i + 1;
    }
    return need;
}

/// Plan 610 ⑤: C ABI export face for `autoterm_engine_cursor` — the sibling wrapper bridges C widths
/// to the safe body below; the exported symbol equals the fn name (no_mangle
/// ignores the module path).
mod autoterm_engine_cursor_c_export {
    use super::*;
    #[unsafe(no_mangle)]
    pub extern "C" fn autoterm_engine_cursor(h: *mut EngineFace, out_row: *mut u32, out_col: *mut u32) -> i32 {
        match unsafe { h.as_mut() } { Some(h) => super::autoterm_engine_cursor(h, out_row, out_col) as i32, None => -1 }
    }
}
fn autoterm_engine_cursor(h: &mut EngineFace, out_row: *mut u32, out_col: *mut u32) -> i64 {
    let cur = h.inner.term.cursor();
    return (cabi_write_opt_tuple2_u32(cur, out_row, out_col) as i64);
}

/// Plan 610 ⑤: C ABI export face for `autoterm_engine_resize` — the sibling wrapper bridges C widths
/// to the safe body below; the exported symbol equals the fn name (no_mangle
/// ignores the module path).
mod autoterm_engine_resize_c_export {
    use super::*;
    #[unsafe(no_mangle)]
    pub extern "C" fn autoterm_engine_resize(h: *mut EngineFace, cols: i32, rows: i32) {
        match unsafe { h.as_mut() } { Some(h) => super::autoterm_engine_resize(h, cols as i64, rows as i64), None => () }
    }
}
fn autoterm_engine_resize(h: &mut EngineFace, cols: i64, rows: i64) {
    h.inner.resize(default_cols(cols), default_rows(rows));
}

/// Plan 610 ⑤: C ABI export face for `autoterm_engine_interrupt` — the sibling wrapper bridges C widths
/// to the safe body below; the exported symbol equals the fn name (no_mangle
/// ignores the module path).
mod autoterm_engine_interrupt_c_export {
    use super::*;
    #[unsafe(no_mangle)]
    pub extern "C" fn autoterm_engine_interrupt(h: *mut EngineFace) -> i32 {
        match unsafe { h.as_mut() } { Some(h) => super::autoterm_engine_interrupt(h) as i32, None => -1 }
    }
}
fn autoterm_engine_interrupt(h: &mut EngineFace) -> i64 {
    if h.inner.interrupt() {
        return 1;
    }
    return 0;
}

/// Plan 610 ⑤: C ABI export face for `autoterm_engine_is_exited` — the sibling wrapper bridges C widths
/// to the safe body below; the exported symbol equals the fn name (no_mangle
/// ignores the module path).
mod autoterm_engine_is_exited_c_export {
    use super::*;
    #[unsafe(no_mangle)]
    pub extern "C" fn autoterm_engine_is_exited(h: *mut EngineFace) -> i32 {
        match unsafe { h.as_mut() } { Some(h) => super::autoterm_engine_is_exited(h) as i32, None => -1 }
    }
}
fn autoterm_engine_is_exited(h: &mut EngineFace) -> i64 {
    if h.inner.exited() {
        return 1;
    }
    return 0;
}

/// Plan 610 ⑤: C ABI export face for `autoterm_engine_kill` — the sibling wrapper bridges C widths
/// to the safe body below; the exported symbol equals the fn name (no_mangle
/// ignores the module path).
mod autoterm_engine_kill_c_export {
    use super::*;
    #[unsafe(no_mangle)]
    pub extern "C" fn autoterm_engine_kill(h: *mut EngineFace) {
        match unsafe { h.as_mut() } { Some(h) => super::autoterm_engine_kill(h), None => () }
    }
}
fn autoterm_engine_kill(h: &mut EngineFace) {
    h.inner.kill();
}

/// Plan 610 ⑤: C ABI export face for `autoterm_engine_free` — the sibling wrapper bridges C widths
/// to the safe body below; the exported symbol equals the fn name (no_mangle
/// ignores the module path).
mod autoterm_engine_free_c_export {
    use super::*;
    #[unsafe(no_mangle)]
    pub extern "C" fn autoterm_engine_free(h: *mut std::ffi::c_void) {
        super::autoterm_engine_free(h)
    }
}
fn autoterm_engine_free(h: *mut std::ffi::c_void) {
    cabi_drop_boxed((h as *mut EngineFace));
}

fn main() {
    println!("engine_face_auto: 12-symbol #[export] face");
}
