// Auto-generated by a2r transpiler

use crate::term::{engine_spawn_ex, engine_free, engine_write_line, engine_rows_for, engine_pump_for, engine_apply_resize_for, engine_viewport_cols, engine_viewport_rows, engine_cursor_row, engine_cursor_col, engine_backlog_pending_mb, engine_backlog_paused, engine_backlog_take_alerts, engine_backlog_dropped, engine_interrupt, engine_is_exited, engine_menu_take, window_width, window_height, config_profiles, config_default_profile, config_profiles_full, config_spawn_program, config_spawn_argv, config_spawn_cwd, engine_scroll_pending_for};
use once_cell::sync::Lazy;
use std::sync::Mutex;

static PANE_IDS: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

static PANE_HANDLES: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

static PANE_KEYS: Lazy<Mutex<Vec<String>>> = Lazy::new(|| Mutex::new(vec![]));

static PANE_TAB_IDS: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

static PANE_PROGRAMS: Lazy<Mutex<Vec<String>>> = Lazy::new(|| Mutex::new(vec![]));

static PANE_CWDS: Lazy<Mutex<Vec<String>>> = Lazy::new(|| Mutex::new(vec![]));

static PANE_COLS: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

static PANE_ROWS: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

static PANE_EXITED: Lazy<Mutex<Vec<bool>>> = Lazy::new(|| Mutex::new(vec![]));

static TAB_IDS: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

static TAB_ROOT_NODE: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

static TAB_ACTIVE_PANE: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

static TAB_ZOOMED_PANE: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

static NODE_IDS: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

static NODE_TAB_IDS: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

static NODE_AXIS: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

static NODE_RATIO: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

static NODE_FIRST: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

static NODE_SECOND: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

static NODE_PANE: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

static WS_ACTIVE_TAB: Mutex<i64> = Mutex::new(0);

static NEXT_PANE_ID: Mutex<i64> = Mutex::new(1);

static NEXT_TAB_ID: Mutex<i64> = Mutex::new(1);

static NEXT_NODE_ID: Mutex<i64> = Mutex::new(1);

static MAX_PANES: Mutex<i64> = Mutex::new(6);

static MAGNET_TARGET: Mutex<i64> = Mutex::new(500);

static MAGNET_THRESH: Mutex<i64> = Mutex::new(40);

static MIN_PANE: Mutex<i64> = Mutex::new(100);

static LAYOUT_EPOCH: Mutex<i64> = Mutex::new(0);

static RECT_CACHE_EPOCH: Lazy<Mutex<i64>> = Lazy::new(|| Mutex::new(-1));

static RECT_KIND: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

static RECT_PANE: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

static RECT_KEY: Lazy<Mutex<Vec<String>>> = Lazy::new(|| Mutex::new(vec![]));

static RECT_BRANCH: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

static RECT_AXIS: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

static RECT_X: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

static RECT_Y: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

static RECT_W: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

static RECT_H: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

static ACT_CODES: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

static ACT_ARGS: Lazy<Mutex<Vec<i64>>> = Lazy::new(|| Mutex::new(vec![]));

static COLS: Mutex<i64> = Mutex::new(100);

static ROWS: Mutex<i64> = Mutex::new(30);

static EXITED: Mutex<bool> = Mutex::new(false);

static BOOTED: Mutex<bool> = Mutex::new(false);

static BL_ALERTS_TOTAL: Mutex<i64> = Mutex::new(0);

static BL_PENDING_MB: Mutex<i64> = Mutex::new(0);

static BL_PAUSED: Mutex<i64> = Mutex::new(0);

static BL_DROPPED: Mutex<i64> = Mutex::new(0);

/// 首调判定(banner 短轮询只挂 boot 拍)。
/// 首调判定(banner 短轮询只挂 boot 拍)。
fn list_remove_int(mut xs: Vec<i64>, idx: i64) -> Vec<i64> {
    let mut out: Vec<i64> = vec![];
    let mut i: i64 = 0;
    let mut n: i64 = (xs.len() as i64);
    loop {
        if i >= n {
            break;
        }
        if i != idx {
            out.push(xs[(i) as usize].clone());
        }
        i = i + 1;
    }
    return out;
}

fn list_remove_str(mut xs: Vec<String>, idx: i64) -> Vec<String> {
    let mut out: Vec<String> = vec![];
    let mut i: i64 = 0;
    let mut n: i64 = (xs.len() as i64);
    loop {
        if i >= n {
            break;
        }
        if i != idx {
            out.push(xs[(i) as usize].clone());
        }
        i = i + 1;
    }
    return out;
}

fn list_remove_bool(mut xs: Vec<bool>, idx: i64) -> Vec<bool> {
    let mut out: Vec<bool> = vec![];
    let mut i: i64 = 0;
    let mut n: i64 = (xs.len() as i64);
    loop {
        if i >= n {
            break;
        }
        if i != idx {
            out.push(xs[(i) as usize].clone());
        }
        i = i + 1;
    }
    return out;
}

fn pane_index(pane_id: i64) -> i64 {
    let mut i: i64 = 0;
    let mut n: i64 = ((*PANE_IDS.lock().unwrap()).len() as i64);
    let mut hit: i64 = -1;
    loop {
        if i >= n {
            break;
        }
        if (*PANE_IDS.lock().unwrap())[(i) as usize].clone() == pane_id {
            hit = i;
        }
        i = i + 1;
    }
    return hit;
}

fn node_index(node_id: i64) -> i64 {
    let mut i: i64 = 0;
    let mut n: i64 = ((*NODE_IDS.lock().unwrap()).len() as i64);
    let mut hit: i64 = -1;
    loop {
        if i >= n {
            break;
        }
        if (*NODE_IDS.lock().unwrap())[(i) as usize].clone() == node_id {
            hit = i;
        }
        i = i + 1;
    }
    return hit;
}

fn tab_index(tab_id: i64) -> i64 {
    let mut i: i64 = 0;
    let mut n: i64 = ((*TAB_IDS.lock().unwrap()).len() as i64);
    let mut hit: i64 = -1;
    loop {
        if i >= n {
            break;
        }
        if (*TAB_IDS.lock().unwrap())[(i) as usize].clone() == tab_id {
            hit = i;
        }
        i = i + 1;
    }
    return hit;
}

/// List<int> 成员判定(泵可见性集合用;V1 规模个位数)。
fn contains_int(mut xs: Vec<i64>, v: i64) -> bool {
    let mut i: i64 = 0;
    let mut n: i64 = (xs.len() as i64);
    loop {
        if i >= n {
            break;
        }
        if xs[(i) as usize].clone() == v {
            return true;
        }
        i = i + 1;
    }
    return false;
}

/// 活动下标(未初始化 = -1)。
fn active_tab_index() -> i64 {
    if (*WS_ACTIVE_TAB.lock().unwrap()) == 0 {
        return -1;
    }
    return tab_index((*WS_ACTIVE_TAB.lock().unwrap()));
}

/// 找 pane 所在叶节点 id(0 = 无)。
fn leaf_node_of_pane(pane_id: i64) -> i64 {
    let mut i: i64 = 0;
    let mut n: i64 = ((*NODE_IDS.lock().unwrap()).len() as i64);
    let mut hit: i64 = 0;
    loop {
        if i >= n {
            break;
        }
        if (*NODE_PANE.lock().unwrap())[(i) as usize].clone() == pane_id {
            hit = (*NODE_IDS.lock().unwrap())[(i) as usize].clone();
        }
        i = i + 1;
    }
    return hit;
}

/// 子树内最左叶的 pane id(close 后焦点回落用;0 = 空)。
fn leftmost_pane(node_id: i64) -> i64 {
    let mut ni: i64 = node_index(node_id);
    if ni < 0 {
        return 0;
    }
    let mut pane: i64 = (*NODE_PANE.lock().unwrap())[(ni) as usize].clone();
    if pane != 0 {
        return pane;
    }
    let mut left: i64 = leftmost_pane((*NODE_FIRST.lock().unwrap())[(ni) as usize].clone());
    if left != 0 {
        return left;
    }
    return leftmost_pane((*NODE_SECOND.lock().unwrap())[(ni) as usize].clone());
}

/// 把树中 old_child 的挂点改挂 new_child(父分支槽或 tab 根)。
fn replace_child(tab_id: i64, old_child: i64, new_child: i64) -> i64 {
    let mut ti: i64 = tab_index(tab_id);
    if ti >= 0 {
        if (*TAB_ROOT_NODE.lock().unwrap())[(ti) as usize].clone() == old_child {
            (*TAB_ROOT_NODE.lock().unwrap())[(ti) as usize] = new_child;
            return 1;
        }    }
    let mut i: i64 = 0;
    let mut n: i64 = ((*NODE_IDS.lock().unwrap()).len() as i64);
    loop {
        if i >= n {
            break;
        }
        

        if (*NODE_IDS.lock().unwrap())[(i) as usize].clone() != new_child {
            if (*NODE_FIRST.lock().unwrap())[(i) as usize].clone() == old_child {
                (*NODE_FIRST.lock().unwrap())[(i) as usize] = new_child;
            }            if (*NODE_SECOND.lock().unwrap())[(i) as usize].clone() == old_child {
                (*NODE_SECOND.lock().unwrap())[(i) as usize] = new_child;
            }        }
        i = i + 1;
    }
    return 1;
}

/// 摘除节点(按 id 重建全部节点表)。
fn drop_node(node_id: i64) -> i64 {
    let mut ni: i64 = node_index(node_id);
    if ni < 0 {
        return 0;
    }
    { let __a2r_gv = list_remove_int((*NODE_IDS.lock().unwrap()).clone(), ni); *NODE_IDS.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = list_remove_int((*NODE_TAB_IDS.lock().unwrap()).clone(), ni); *NODE_TAB_IDS.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = list_remove_int((*NODE_AXIS.lock().unwrap()).clone(), ni); *NODE_AXIS.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = list_remove_int((*NODE_RATIO.lock().unwrap()).clone(), ni); *NODE_RATIO.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = list_remove_int((*NODE_FIRST.lock().unwrap()).clone(), ni); *NODE_FIRST.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = list_remove_int((*NODE_SECOND.lock().unwrap()).clone(), ni); *NODE_SECOND.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = list_remove_int((*NODE_PANE.lock().unwrap()).clone(), ni); *NODE_PANE.lock().unwrap() = __a2r_gv; };
    return 1;
}

/// 摘除 Pane(按下标重建全部 pane 表;句柄释放由调用方先行)。
fn remove_pane_at(pi: i64) -> i64 {
    { let __a2r_gv = list_remove_int((*PANE_IDS.lock().unwrap()).clone(), pi); *PANE_IDS.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = list_remove_int((*PANE_HANDLES.lock().unwrap()).clone(), pi); *PANE_HANDLES.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = list_remove_str((*PANE_KEYS.lock().unwrap()).clone(), pi); *PANE_KEYS.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = list_remove_int((*PANE_TAB_IDS.lock().unwrap()).clone(), pi); *PANE_TAB_IDS.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = list_remove_str((*PANE_PROGRAMS.lock().unwrap()).clone(), pi); *PANE_PROGRAMS.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = list_remove_str((*PANE_CWDS.lock().unwrap()).clone(), pi); *PANE_CWDS.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = list_remove_int((*PANE_COLS.lock().unwrap()).clone(), pi); *PANE_COLS.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = list_remove_int((*PANE_ROWS.lock().unwrap()).clone(), pi); *PANE_ROWS.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = list_remove_bool((*PANE_EXITED.lock().unwrap()).clone(), pi); *PANE_EXITED.lock().unwrap() = __a2r_gv; };
    return 1;
}

/// 结构变异后失效矩形投影缓存(PLAN-020 D1;纯计数,廉价)。
fn bump_layout_epoch() -> i64 {
    { let __a2r_gv = (*LAYOUT_EPOCH.lock().unwrap()) + 1; *LAYOUT_EPOCH.lock().unwrap() = __a2r_gv; };
    return (*LAYOUT_EPOCH.lock().unwrap());
}

/// 矩形投影(PLAN-020 D1):对活动 Tab 可见子树做层序(BFS)遍历,
/// 产出 pane 槽(≤MAX_PANES)与 divider 槽(≤MAX_PANES−1)的归一化
/// 矩形(‰)。zoom 投影 = 单 pane 槽满幅、零 divider。纯循环 + 平行
/// List 队列(018 平面表惯例;树深不限)。结果落缓存,getter 消费。
fn rects_recompute() -> i64 {
    { let __a2r_gv = vec![]; *RECT_KIND.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = vec![]; *RECT_PANE.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = vec![]; *RECT_KEY.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = vec![]; *RECT_BRANCH.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = vec![]; *RECT_AXIS.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = vec![]; *RECT_X.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = vec![]; *RECT_Y.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = vec![]; *RECT_W.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = vec![]; *RECT_H.lock().unwrap() = __a2r_gv; };
    let mut ti: i64 = active_tab_index();
    if ti < 0 {
        { let __a2r_gv = (*LAYOUT_EPOCH.lock().unwrap()); *RECT_CACHE_EPOCH.lock().unwrap() = __a2r_gv; };
        return 0;
    }
    let mut zoomed: i64 = (*TAB_ZOOMED_PANE.lock().unwrap())[(ti) as usize].clone();
    if zoomed != 0 {
        

        (*RECT_KIND.lock().unwrap()).push(1);
        (*RECT_PANE.lock().unwrap()).push(zoomed);
        let mut pi: i64 = pane_index(zoomed);
        if pi >= 0 {
            (*RECT_KEY.lock().unwrap()).push((*PANE_KEYS.lock().unwrap())[(pi) as usize].clone());
        } else {
            (*RECT_KEY.lock().unwrap()).push("".to_string());
        }
        (*RECT_BRANCH.lock().unwrap()).push(0);
        (*RECT_AXIS.lock().unwrap()).push(-1);
        (*RECT_X.lock().unwrap()).push(0);
        (*RECT_Y.lock().unwrap()).push(0);
        (*RECT_W.lock().unwrap()).push(1000);
        (*RECT_H.lock().unwrap()).push(1000);
        { let __a2r_gv = (*LAYOUT_EPOCH.lock().unwrap()); *RECT_CACHE_EPOCH.lock().unwrap() = __a2r_gv; };
        return 1;
    }


    let mut p_kind: Vec<i64> = vec![];
    let mut p_pane: Vec<i64> = vec![];
    let mut p_key: Vec<String> = vec![];
    let mut p_x: Vec<i64> = vec![];
    let mut p_y: Vec<i64> = vec![];
    let mut p_w: Vec<i64> = vec![];
    let mut p_h: Vec<i64> = vec![];
    let mut d_kind: Vec<i64> = vec![];
    let mut d_branch: Vec<i64> = vec![];
    let mut d_axis: Vec<i64> = vec![];
    let mut d_x: Vec<i64> = vec![];
    let mut d_y: Vec<i64> = vec![];
    let mut d_w: Vec<i64> = vec![];
    let mut d_h: Vec<i64> = vec![];

    let mut q_node: Vec<i64> = vec![];
    let mut q_x: Vec<i64> = vec![];
    let mut q_y: Vec<i64> = vec![];
    let mut q_w: Vec<i64> = vec![];
    let mut q_h: Vec<i64> = vec![];
    q_node.push((*TAB_ROOT_NODE.lock().unwrap())[(ti) as usize].clone());
    q_x.push(0);
    q_y.push(0);
    q_w.push(1000);
    q_h.push(1000);



    let mut head: i64 = 0;
    let mut steps: i64 = 0;
    loop {
        if head >= q_node.len() as i64 {
            break;
        }
        if steps >= 512 {
            break;
        }
        if (q_node.len() as i64) > 256 {
            break;
        }
        steps = steps + 1;
        let mut nid: i64 = q_node[(head) as usize].clone();
        let mut nx: i64 = q_x[(head) as usize].clone();
        let mut ny: i64 = q_y[(head) as usize].clone();
        let mut nw: i64 = q_w[(head) as usize].clone();
        let mut nh: i64 = q_h[(head) as usize].clone();
        head = head + 1;
        let mut ni: i64 = node_index(nid);
        if ni >= 0 {
            let mut pane: i64 = (*NODE_PANE.lock().unwrap())[(ni) as usize].clone();
            if pane != 0 {
                

                p_kind.push(1);
                p_pane.push(pane);
                p_key.push((*PANE_KEYS.lock().unwrap())[(pane_index(pane)) as usize].clone());
                p_x.push(nx);
                p_y.push(ny);
                p_w.push(nw);
                p_h.push(nh);
            } else {
                


                let mut axis: i64 = (*NODE_AXIS.lock().unwrap())[(ni) as usize].clone();
                let mut ratio: i64 = (*NODE_RATIO.lock().unwrap())[(ni) as usize].clone();
                d_kind.push(2);
                d_branch.push(nid);
                d_axis.push(axis);
                if axis == 1 {
                    d_x.push(nx + nw * ratio / 1000);
                    d_y.push(ny);
                    d_w.push(0);
                    d_h.push(nh);
                } else {
                    d_x.push(nx);
                    d_y.push(ny + nh * ratio / 1000);
                    d_w.push(nw);
                    d_h.push(0);
                }
                let mut fw: i64 = nw;
                let mut fh: i64 = nh;
                let mut sx: i64 = nx;
                let mut sy: i64 = ny;
                if axis == 1 {
                    fw = nw * ratio / 1000;
                    sx = nx + fw;
                } else {
                    fh = nh * ratio / 1000;
                    sy = ny + fh;
                }
                q_node.push((*NODE_FIRST.lock().unwrap())[(ni) as usize].clone());
                q_x.push(nx);
                q_y.push(ny);
                q_w.push(fw);
                q_h.push(fh);
                q_node.push((*NODE_SECOND.lock().unwrap())[(ni) as usize].clone());
                q_x.push(sx);
                q_y.push(sy);
                


                if axis == 1 {
                    q_w.push(nw - fw);
                    q_h.push(nh);
                } else {
                    q_w.push(nw);
                    q_h.push(nh - fh);
                }
            }
        }
    }


    let mut i: i64 = 0;
    loop {
        if i >= (*MAX_PANES.lock().unwrap()) {
            break;
        }
        if i < p_kind.len() as i64 {
            (*RECT_KIND.lock().unwrap()).push(p_kind[(i) as usize].clone());
            (*RECT_PANE.lock().unwrap()).push(p_pane[(i) as usize].clone());
            (*RECT_KEY.lock().unwrap()).push(p_key[(i) as usize].clone());
            (*RECT_X.lock().unwrap()).push(p_x[(i) as usize].clone());
            (*RECT_Y.lock().unwrap()).push(p_y[(i) as usize].clone());
            (*RECT_W.lock().unwrap()).push(p_w[(i) as usize].clone());
            (*RECT_H.lock().unwrap()).push(p_h[(i) as usize].clone());
        } else {
            (*RECT_KIND.lock().unwrap()).push(0);
            (*RECT_PANE.lock().unwrap()).push(0);
            (*RECT_KEY.lock().unwrap()).push("".to_string());
            (*RECT_X.lock().unwrap()).push(0);
            (*RECT_Y.lock().unwrap()).push(0);
            (*RECT_W.lock().unwrap()).push(0);
            (*RECT_H.lock().unwrap()).push(0);
        }

        (*RECT_BRANCH.lock().unwrap()).push(0);
        (*RECT_AXIS.lock().unwrap()).push(-1);
        i = i + 1;
    }
    i = 0;
    loop {
        if i >= d_kind.len() as i64 {
            break;
        }
        (*RECT_KIND.lock().unwrap()).push(d_kind[(i) as usize].clone());
        (*RECT_PANE.lock().unwrap()).push(0);
        (*RECT_KEY.lock().unwrap()).push("".to_string());
        (*RECT_BRANCH.lock().unwrap()).push(d_branch[(i) as usize].clone());
        (*RECT_AXIS.lock().unwrap()).push(d_axis[(i) as usize].clone());
        (*RECT_X.lock().unwrap()).push(d_x[(i) as usize].clone());
        (*RECT_Y.lock().unwrap()).push(d_y[(i) as usize].clone());
        (*RECT_W.lock().unwrap()).push(d_w[(i) as usize].clone());
        (*RECT_H.lock().unwrap()).push(d_h[(i) as usize].clone());
        i = i + 1;
    }
    { let __a2r_gv = (*LAYOUT_EPOCH.lock().unwrap()); *RECT_CACHE_EPOCH.lock().unwrap() = __a2r_gv; };
    return 1;
}

/// 投影缓存就绪(惰性重建;epoch 失效)。
fn rects_ready() -> i64 {
    if (*RECT_CACHE_EPOCH.lock().unwrap()) != (*LAYOUT_EPOCH.lock().unwrap()) {
        rects_recompute();
    }
    return 1;
}

/// 第 k 槽字段读取(k 1 起;越界 = 缺省)。plan:窗格/分隔条统一槽表。
fn rect_at(mut kind: Vec<i64>, k: i64) -> i64 {
    if k < 1 {
        return 0;
    }
    if k > kind.len() as i64 {
        return 0;
    }
    return kind[(k - 1) as usize].clone();
}

pub fn mux_rect_kind(k: i64) -> i64 {
    rects_ready();
    return rect_at((*RECT_KIND.lock().unwrap()).clone(), k);
}

pub fn mux_rect_pane(k: i64) -> i64 {
    rects_ready();
    return rect_at((*RECT_PANE.lock().unwrap()).clone(), k);
}

pub fn mux_rect_key(k: i64) -> String {
    rects_ready();
    if k < 1 {
        return "".to_string();
    }
    if k > (*RECT_KEY.lock().unwrap()).len() as i64 {
        return "".to_string();
    }
    return (*RECT_KEY.lock().unwrap())[(k - 1) as usize].clone();
}

pub fn mux_rect_branch(k: i64) -> i64 {
    rects_ready();
    return rect_at((*RECT_BRANCH.lock().unwrap()).clone(), k);
}

pub fn mux_rect_axis(k: i64) -> i64 {
    rects_ready();
    return rect_at((*RECT_AXIS.lock().unwrap()).clone(), k);
}

pub fn mux_rect_x(k: i64) -> i64 {
    rects_ready();
    return rect_at((*RECT_X.lock().unwrap()).clone(), k);
}

pub fn mux_rect_y(k: i64) -> i64 {
    rects_ready();
    return rect_at((*RECT_Y.lock().unwrap()).clone(), k);
}

pub fn mux_rect_w(k: i64) -> i64 {
    rects_ready();
    return rect_at((*RECT_W.lock().unwrap()).clone(), k);
}

pub fn mux_rect_h(k: i64) -> i64 {
    rects_ready();
    return rect_at((*RECT_H.lock().unwrap()).clone(), k);
}

pub fn mux_layout_version() -> i64 {
    return (*LAYOUT_EPOCH.lock().unwrap());
}

pub fn mux_window_width() -> i64 {
    return window_width();
}

pub fn mux_window_height() -> i64 {
    return window_height();
}

/// 第 k 槽类型(0=空 1=pane 2=divider)。
/// 第 k 槽 pane 模型 key(pane 槽;空 = 非 pane 槽)。
/// 投影版本号(PLAN-020 复审 F1:layout_version 门控)——结构变异时
/// 递增的廉价读;前端每拍先读本值,变化才拉完整 rect-*(把稳态请求量
/// 压回 019 水位,降低 axum 并发与引擎 FFI 争用窗口)。
/// 窗口客户区逻辑 px(PLAN-020 T-00b 窗口尺寸面;矩形投影 px 类
/// 几何的标定源。VM = shim 读渲染器每帧全局;rust = 侧车同名;vue
/// back 降级缺省槽位值)。
/// 当前 Tab 根分支的矩形(‰;(0,0,1000,1000) = 无分屏/未初始化)。
/// mux_resize_branch 的比例换算基准(D2;与投影同一 BFS 语义)。
fn rect_of_node(node_id: i64) -> Vec<i64> {
    let mut out: Vec<i64> = vec![0, 0, 1000, 1000];
    let mut ni: i64 = node_index(node_id);
    if ni < 0 {
        return out;
    }
    let mut ti: i64 = tab_index((*NODE_TAB_IDS.lock().unwrap())[(ni) as usize].clone());
    if ti < 0 {
        return out;
    }

    let mut s_node: Vec<i64> = vec![];
    let mut s_x: Vec<i64> = vec![];
    let mut s_y: Vec<i64> = vec![];
    let mut s_w: Vec<i64> = vec![];
    let mut s_h: Vec<i64> = vec![];
    s_node.push((*TAB_ROOT_NODE.lock().unwrap())[(ti) as usize].clone());
    s_x.push(0);
    s_y.push(0);
    s_w.push(1000);
    s_h.push(1000);
    let mut guard: i64 = 0;
    loop {
        if (s_node.len() as i64) == 0 {
            break;
        }
        if guard >= 512 {
            break;
        }
        if (s_node.len() as i64) > 256 {
            break;
        }
        guard = guard + 1;
        let mut nid: i64 = s_node[((s_node.len() as i64) - 1) as usize].clone();
        let mut nx: i64 = s_x[((s_x.len() as i64) - 1) as usize].clone();
        let mut ny: i64 = s_y[((s_y.len() as i64) - 1) as usize].clone();
        let mut nw: i64 = s_w[((s_w.len() as i64) - 1) as usize].clone();
        let mut nh: i64 = s_h[((s_h.len() as i64) - 1) as usize].clone();
        s_node = list_remove_int(s_node.clone(), (s_node.len() as i64) - 1);
        s_x = list_remove_int(s_x.clone(), (s_x.len() as i64) - 1);
        s_y = list_remove_int(s_y.clone(), (s_y.len() as i64) - 1);
        s_w = list_remove_int(s_w.clone(), (s_w.len() as i64) - 1);
        s_h = list_remove_int(s_h.clone(), (s_h.len() as i64) - 1);
        let mut ci: i64 = node_index(nid);
        if nid == node_id {
            out = vec![nx, ny, nw, nh];
            return out;
        }
        if ci >= 0 {
            if (*NODE_PANE.lock().unwrap())[(ci) as usize].clone() == 0 {
                let mut axis: i64 = (*NODE_AXIS.lock().unwrap())[(ci) as usize].clone();
                let mut ratio: i64 = (*NODE_RATIO.lock().unwrap())[(ci) as usize].clone();
                let mut fw: i64 = nw;
                let mut fh: i64 = nh;
                let mut sx: i64 = nx;
                let mut sy: i64 = ny;
                if axis == 1 {
                    fw = nw * ratio / 1000;
                    sx = nx + fw;
                } else {
                    fh = nh * ratio / 1000;
                    sy = ny + fh;
                }
                s_node.push((*NODE_FIRST.lock().unwrap())[(ci) as usize].clone());
                s_x.push(nx);
                s_y.push(ny);
                s_w.push(fw);
                s_h.push(fh);
                s_node.push((*NODE_SECOND.lock().unwrap())[(ci) as usize].clone());
                s_x.push(sx);
                s_y.push(sy);
                if axis == 1 {
                    s_w.push(nw - fw);
                    s_h.push(nh);
                } else {
                    s_w.push(nw);
                    s_h.push(nh - fh);
                }
            }        }
    }
    return out;
}

pub fn mux_resize_branch(branch_id: i64, px: i64, py: i64) -> i64 {
    let mut ni: i64 = node_index(branch_id);
    if ni < 0 {
        return -1;
    }
    if (*NODE_PANE.lock().unwrap())[(ni) as usize].clone() != 0 {
        return -1;
    }
    let mut rect: Vec<i64> = rect_of_node(branch_id);
    let mut bx: i64 = rect[(0) as usize].clone();
    let mut by: i64 = rect[(1) as usize].clone();
    let mut bw: i64 = rect[(2) as usize].clone();
    let mut bh: i64 = rect[(3) as usize].clone();
    let mut axis: i64 = (*NODE_AXIS.lock().unwrap())[(ni) as usize].clone();
    let mut ratio: i64 = 0;
    if axis == 1 {
        if bw <= 0 {
            return -1;
        }        ratio = (px - bx) * 1000 / bw;
    } else {
        if bh <= 0 {
            return -1;
        }        ratio = (py - by) * 1000 / bh;
    }

    if ratio < (*MIN_PANE.lock().unwrap()) {
        ratio = (*MIN_PANE.lock().unwrap());
    }
    if ratio > 1000 - (*MIN_PANE.lock().unwrap()) {
        ratio = 1000 - (*MIN_PANE.lock().unwrap());
    }
    let mut d: i64 = ratio - (*MAGNET_TARGET.lock().unwrap());
    if d < 0 {
        d = 0 - d;
    }
    if d <= (*MAGNET_THRESH.lock().unwrap()) {
        ratio = (*MAGNET_TARGET.lock().unwrap());
    }
    (*NODE_RATIO.lock().unwrap())[(ni) as usize] = ratio;
    bump_layout_epoch();
    return ratio;
}

/// 分支级调比例(PLAN-020 D2;拖拽唯一写入口,键盘委托同此)。
/// (px,py) = 指针在内容区的 ‰ 坐标(前端捕获层 coords 归一,取整后
/// 传入;1‰ ≈ 1 格距,精度充分)。比例 = 指针沿分支轴在父矩形内的
/// 位置;钳位 [MIN_PANE, 1000−MIN_PANE];磁吸 |r−500|≤40 → 500。
/// 返回落定比例(负 = 未找到/叶无比例)。
/// 活动焦点 Pane id(0 = 无)。
fn mux_focus_pane_id() -> i64 {
    let mut ti: i64 = active_tab_index();
    if ti < 0 {
        return 0;
    }
    return (*TAB_ACTIVE_PANE.lock().unwrap())[(ti) as usize].clone();
}

/// 焦点 Pane 的引擎柄(0 = 无/未初始化)。
fn mux_focus_handle() -> i64 {
    let mut pid: i64 = mux_focus_pane_id();
    if pid == 0 {
        return 0;
    }
    let mut pi: i64 = pane_index(pid);
    if pi < 0 {
        return 0;
    }
    return (*PANE_HANDLES.lock().unwrap())[(pi) as usize].clone();
}

/// 焦点 Pane 的模型 key(pane-<id>;"" = 无)。
fn mux_focus_key_inner() -> String {
    let mut pid: i64 = mux_focus_pane_id();
    if pid == 0 {
        return "".to_string();
    }
    let mut pi: i64 = pane_index(pid);
    if pi < 0 {
        return "".to_string();
    }
    return (*PANE_KEYS.lock().unwrap())[(pi) as usize].clone();
}

/// 当前 Tab 可见 pane id 表(PLAN-019 D1 泵三档判据源)。
/// zoom 投影:zoom 中仅 zoomed Pane 可见;否则 = 当前 Tab 全部 Pane。
fn mux_visible_pane_ids() -> Vec<i64> {
    let mut out: Vec<i64> = vec![];
    let mut ti: i64 = active_tab_index();
    if ti < 0 {
        return out;
    }
    let mut zoomed: i64 = (*TAB_ZOOMED_PANE.lock().unwrap())[(ti) as usize].clone();
    if zoomed != 0 {
        out.push(zoomed);
        return out;
    }
    let mut i: i64 = 0;
    let mut n: i64 = ((*PANE_IDS.lock().unwrap()).len() as i64);
    loop {
        if i >= n {
            break;
        }
        if (*PANE_TAB_IDS.lock().unwrap())[(i) as usize].clone() == (*WS_ACTIVE_TAB.lock().unwrap()) {
            out.push((*PANE_IDS.lock().unwrap())[(i) as usize].clone());
        }
        i = i + 1;
    }
    return out;
}

/// 建新 Pane(引擎 spawn + 表落账)→ 返回其叶节点 id(0 = 失败)。
/// PLAN-025 T-07:profile 参数("" = default_profile)——命中经
/// SpawnSpec(program/argv/cwd)spawn_ex;未命中回落缺省 shell
/// (COMSPEC,引擎 FFI default_shell 兜底,G6)。
fn spawn_pane_into_tab(tab_id: i64, axis: i64, profile: &str) -> i64 {
    let mut pid: i64 = (*NEXT_PANE_ID.lock().unwrap());
    { let __a2r_gv = (*NEXT_PANE_ID.lock().unwrap()) + 1; *NEXT_PANE_ID.lock().unwrap() = __a2r_gv; };
    let mut key: String = format!("{}{}", "pane-", pid.to_string());
    let mut program: String = config_spawn_program(profile);
    let mut h: i64 = 0;
    if program != "" {
        let mut argv: Vec<String> = config_spawn_argv(profile);
        let mut cwd: String = config_spawn_cwd(profile);
        h = engine_spawn_ex(program.as_str(), argv, cwd.as_str(), 100, 30);
    } else {
        h = engine_spawn_ex("", vec![], "", 100, 30);
    }

    if h == 0 {
        return 0;
    }
    (*PANE_IDS.lock().unwrap()).push(pid);
    (*PANE_HANDLES.lock().unwrap()).push(h);
    (*PANE_KEYS.lock().unwrap()).push(key.to_string());
    (*PANE_TAB_IDS.lock().unwrap()).push(tab_id);
    (*PANE_PROGRAMS.lock().unwrap()).push(program.to_string());
    (*PANE_CWDS.lock().unwrap()).push("".to_string());
    (*PANE_COLS.lock().unwrap()).push(100);
    (*PANE_ROWS.lock().unwrap()).push(30);
    (*PANE_EXITED.lock().unwrap()).push(false);

    let mut leaf: i64 = (*NEXT_NODE_ID.lock().unwrap());
    { let __a2r_gv = (*NEXT_NODE_ID.lock().unwrap()) + 1; *NEXT_NODE_ID.lock().unwrap() = __a2r_gv; };
    (*NODE_IDS.lock().unwrap()).push(leaf);
    (*NODE_TAB_IDS.lock().unwrap()).push(tab_id);
    (*NODE_AXIS.lock().unwrap()).push(axis);
    (*NODE_RATIO.lock().unwrap()).push(500);
    (*NODE_FIRST.lock().unwrap()).push(0);
    (*NODE_SECOND.lock().unwrap()).push(0);
    (*NODE_PANE.lock().unwrap()).push(pid);
    return leaf;
}

pub fn mux_enqueue(code: i64, arg: i64) -> i64 {
    (*ACT_CODES.lock().unwrap()).push(code);
    (*ACT_ARGS.lock().unwrap()).push(arg);
    return 1;
}

pub fn mux_focus_dir(d: i64) -> i64 {
    let mut cur: i64 = mux_focus_pane_id();
    if cur == 0 {
        return 0;
    }
    let mut ci: i64 = -1;
    let mut cx: i64 = 0;
    let mut cy: i64 = 0;
    let mut i: i64 = 0;
    loop {
        if i >= (*MAX_PANES.lock().unwrap()) {
            break;
        }
        if (*RECT_KIND.lock().unwrap())[(i) as usize].clone() == 1 && (*RECT_PANE.lock().unwrap())[(i) as usize].clone() == cur {
            ci = i;
            cx = (*RECT_X.lock().unwrap())[(i) as usize].clone() + (*RECT_W.lock().unwrap())[(i) as usize].clone() / 2;
            cy = (*RECT_Y.lock().unwrap())[(i) as usize].clone() + (*RECT_H.lock().unwrap())[(i) as usize].clone() / 2;
        }
        i = i + 1;
    }
    if ci < 0 {
        return 0;
    }
    let mut best: i64 = -1;
    let mut best_score: i64 = 0;
    i = 0;
    loop {
        if i >= (*MAX_PANES.lock().unwrap()) {
            break;
        }
        if i != ci && (*RECT_KIND.lock().unwrap())[(i) as usize].clone() == 1 {
            let mut ox: i64 = (*RECT_X.lock().unwrap())[(i) as usize].clone() + (*RECT_W.lock().unwrap())[(i) as usize].clone() / 2 - cx;
            let mut oy: i64 = (*RECT_Y.lock().unwrap())[(i) as usize].clone() + (*RECT_H.lock().unwrap())[(i) as usize].clone() / 2 - cy;
            let mut ok: i64 = 0;
            let mut primary: i64 = 0;
            let mut cross: i64 = 0;
            if d == 0 && oy < 0 {
                ok = 1;
                primary = 0 - oy;
                cross = ox;
            }            if d == 1 && oy > 0 {
                ok = 1;
                primary = oy;
                cross = ox;
            }            if d == 2 && ox < 0 {
                ok = 1;
                primary = 0 - ox;
                cross = oy;
            }            if d == 3 && ox > 0 {
                ok = 1;
                primary = ox;
                cross = oy;
            }            if ok == 1 {
                if cross < 0 {
                    cross = 0 - cross;
                }                let mut score: i64 = primary * 1000 + cross;
                if best < 0 || score < best_score {
                    best = (*RECT_PANE.lock().unwrap())[(i) as usize].clone();
                    best_score = score;
                }            }        }
        i = i + 1;
    }
    if best >= 0 {
        return mux_focus(best);
    }
    return 0;
}

/// 用户动作入队(UI 线程安全)。
/// 1=NewTab(arg0) 2=Split(arg=axis) 3=CloseFocusPane(arg=pane id)
/// 4=Zoom(arg=pane id) 5=ActivateTab(arg=tab id) 6=CloseTab(arg=tab id)
/// 方向聚焦导航(PLAN-022 T-06 用户指令:Alt+WASD 切换 split 子窗口)。
/// d 0=上 1=下 2=左 3=右;按 pane 槽位矩形中心选方向半平面内最近邻
/// (主轴×1000 + 正交绝对值评分),命中即切焦;贴边无邻居保持原焦点。
/// zoom 态仅一槽可见,无邻居,自然保持。
/// 动作排水(tick 专用,单线程;每拍至多 8 条防饿死视图)。
fn mux_drain_actions() -> i64 {
    let mut guard: i64 = 0;
    loop {
        if guard >= 8 {
            break;
        }
        if ((*ACT_CODES.lock().unwrap()).len() as i64) == 0 {
            break;
        }
        let mut code: i64 = (*ACT_CODES.lock().unwrap())[(0) as usize].clone();
        let mut arg: i64 = (*ACT_ARGS.lock().unwrap())[(0) as usize].clone();
        { let __a2r_gv = list_remove_int((*ACT_CODES.lock().unwrap()).clone(), 0); *ACT_CODES.lock().unwrap() = __a2r_gv; };
        { let __a2r_gv = list_remove_int((*ACT_ARGS.lock().unwrap()).clone(), 0); *ACT_ARGS.lock().unwrap() = __a2r_gv; };
        if code == 1 {
            

            mux_new_tab(profile_name_of_arg(arg).as_str());
        }
        if code == 2 {
            mux_split(arg);
        }
        if code == 3 {
            let mut fid: i64 = mux_focus_pane_id();
            mux_close_pane(fid);
        }
        if code == 4 {
            mux_zoom(arg);
        }
        if code == 5 {
            mux_activate_tab(arg);
        }
        if code == 6 {
            mux_close_tab(arg);
        }
        guard = guard + 1;
    }
    return 0;
}

pub fn mux_init() -> i64 {
    if (*WS_ACTIVE_TAB.lock().unwrap()) != 0 {
        return 0;
    }
    let mut tab: i64 = mux_new_tab("");
    { let __a2r_gv = tab; *WS_ACTIVE_TAB.lock().unwrap() = __a2r_gv; };
    return tab;
}

/// V1 单 Workspace + 初始 Tab + 初始 Pane(缺省 shell,继承宿主 cwd;
/// 100×30 存档几何)。已初始化 = no-op(0)。
/// PLAN-025 T-07:初始 Pane 按 default_profile spawn(配置缺席回落
/// 缺省 shell,G4/G6)。
/// profile 槽位 → 名字(动作队列编码面:1 起;0/越界 = "" = default)。
fn profile_name_of_arg(arg: i64) -> String {
    if arg <= 0 {
        return "".to_string();
    }
    let mut names: Vec<String> = config_profiles();
    if arg > names.len() as i64 {
        return "".to_string();
    }
    return names[(arg - 1) as usize].clone();
}

pub fn mux_split(axis: i64) -> i64 {
    let mut ti: i64 = active_tab_index();
    if ti < 0 {
        return 0;
    }
    let mut tab_id: i64 = (*TAB_IDS.lock().unwrap())[(ti) as usize].clone();

    let mut cnt: i64 = 0;
    let mut pi: i64 = 0;
    let mut pn: i64 = ((*PANE_IDS.lock().unwrap()).len() as i64);
    loop {
        if pi >= pn {
            break;
        }
        if (*PANE_TAB_IDS.lock().unwrap())[(pi) as usize].clone() == tab_id {
            cnt = cnt + 1;
        }
        pi = pi + 1;
    }
    if cnt >= (*MAX_PANES.lock().unwrap()) {
        return -2;
    }
    let mut focus: i64 = (*TAB_ACTIVE_PANE.lock().unwrap())[(ti) as usize].clone();
    let mut old_leaf: i64 = leaf_node_of_pane(focus);
    if old_leaf == 0 {
        return 0;
    }
    let mut new_leaf: i64 = spawn_pane_into_tab(tab_id, axis, "");
    if new_leaf == 0 {
        return 0;
    }
    let mut branch: i64 = (*NEXT_NODE_ID.lock().unwrap());
    { let __a2r_gv = (*NEXT_NODE_ID.lock().unwrap()) + 1; *NEXT_NODE_ID.lock().unwrap() = __a2r_gv; };
    (*NODE_IDS.lock().unwrap()).push(branch);
    (*NODE_TAB_IDS.lock().unwrap()).push(tab_id);
    (*NODE_AXIS.lock().unwrap()).push(axis);
    (*NODE_RATIO.lock().unwrap()).push(500);
    (*NODE_FIRST.lock().unwrap()).push(0);
    (*NODE_SECOND.lock().unwrap()).push(0);
    (*NODE_PANE.lock().unwrap()).push(0);






    replace_child(tab_id, old_leaf, branch);
    let mut bi: i64 = node_index(branch);
    (*NODE_FIRST.lock().unwrap())[(bi) as usize] = old_leaf;
    (*NODE_SECOND.lock().unwrap())[(bi) as usize] = new_leaf;
    bump_layout_epoch();
    let mut ni: i64 = node_index(new_leaf);
    return (*NODE_PANE.lock().unwrap())[(ni) as usize].clone();
}

pub fn mux_close_pane(pane_id: i64) -> i64 {
    let mut pi: i64 = pane_index(pane_id);
    if pi < 0 {
        return -1;
    }
    let mut tab_id: i64 = (*PANE_TAB_IDS.lock().unwrap())[(pi) as usize].clone();
    let mut leaf: i64 = leaf_node_of_pane(pane_id);
    if leaf == 0 {
        return -1;
    }
    let mut ti2: i64 = tab_index(tab_id);
    if (*TAB_ROOT_NODE.lock().unwrap())[(ti2) as usize].clone() == leaf {
        

        return mux_close_tab(tab_id);
    }

    let mut parent: i64 = 0;
    let mut sibling: i64 = 0;
    let mut i: i64 = 0;
    let mut n: i64 = ((*NODE_IDS.lock().unwrap()).len() as i64);
    loop {
        if i >= n {
            break;
        }
        if (*NODE_FIRST.lock().unwrap())[(i) as usize].clone() == leaf {
            parent = (*NODE_IDS.lock().unwrap())[(i) as usize].clone();
            sibling = (*NODE_SECOND.lock().unwrap())[(i) as usize].clone();
        }
        if (*NODE_SECOND.lock().unwrap())[(i) as usize].clone() == leaf {
            parent = (*NODE_IDS.lock().unwrap())[(i) as usize].clone();
            sibling = (*NODE_FIRST.lock().unwrap())[(i) as usize].clone();
        }
        i = i + 1;
    }
    if parent == 0 {
        return 0;
    }

    replace_child(tab_id, parent, sibling);
    drop_node(parent);
    drop_node(leaf);
    let mut h: i64 = (*PANE_HANDLES.lock().unwrap())[(pi) as usize].clone();
    engine_free(h);
    remove_pane_at(pi);

    if (*TAB_ACTIVE_PANE.lock().unwrap())[(ti2) as usize].clone() == pane_id {
        let mut next_focus: i64 = leftmost_pane(sibling);
        if next_focus != 0 {
            (*TAB_ACTIVE_PANE.lock().unwrap())[(ti2) as usize] = next_focus;
        }    }
    bump_layout_epoch();
    return 1;
}

pub fn mux_focus(pane_id: i64) -> i64 {
    let mut pi: i64 = pane_index(pane_id);
    if pi < 0 {
        return -1;
    }
    let mut tab_id: i64 = (*PANE_TAB_IDS.lock().unwrap())[(pi) as usize].clone();
    let mut ti: i64 = tab_index(tab_id);
    if ti < 0 {
        return -1;
    }
    (*TAB_ACTIVE_PANE.lock().unwrap())[(ti) as usize] = pane_id;
    return 1;
}

pub fn mux_zoom(pane_id: i64) -> i64 {
    let mut ti: i64 = active_tab_index();
    if ti < 0 {
        return -1;
    }
    let mut cur: i64 = (*TAB_ZOOMED_PANE.lock().unwrap())[(ti) as usize].clone();
    if cur == pane_id {
        (*TAB_ZOOMED_PANE.lock().unwrap())[(ti) as usize] = 0;
        bump_layout_epoch();
        return 0;
    }
    (*TAB_ZOOMED_PANE.lock().unwrap())[(ti) as usize] = pane_id;
    bump_layout_epoch();
    return 1;
}

pub fn mux_resize_pane(pane_id: i64, ratio: i64) -> i64 {
    let mut leaf: i64 = leaf_node_of_pane(pane_id);
    if leaf == 0 {
        return -1;
    }
    let mut i: i64 = 0;
    let mut n: i64 = ((*NODE_IDS.lock().unwrap()).len() as i64);
    let mut hit: i64 = -1;
    loop {
        if i >= n {
            break;
        }
        if (*NODE_FIRST.lock().unwrap())[(i) as usize].clone() == leaf {
            hit = i;
        }
        if (*NODE_SECOND.lock().unwrap())[(i) as usize].clone() == leaf {
            hit = i;
        }
        i = i + 1;
    }
    if hit < 0 {
        return -1;
    }
    let mut branch: i64 = (*NODE_IDS.lock().unwrap())[(hit) as usize].clone();
    let mut rect: Vec<i64> = rect_of_node(branch);
    let mut px: i64 = rect[(0) as usize].clone() + rect[(2) as usize].clone() * ratio / 1000;
    let mut py: i64 = rect[(1) as usize].clone() + rect[(3) as usize].clone() * ratio / 1000;
    return mux_resize_branch(branch, px, py);
}

pub fn mux_new_tab(profile: &str) -> i64 {
    let mut tab: i64 = (*NEXT_TAB_ID.lock().unwrap());
    { let __a2r_gv = (*NEXT_TAB_ID.lock().unwrap()) + 1; *NEXT_TAB_ID.lock().unwrap() = __a2r_gv; };
    let mut leaf: i64 = spawn_pane_into_tab(tab, 0, profile);
    if leaf == 0 {
        return 0;
    }
    (*TAB_IDS.lock().unwrap()).push(tab);
    (*TAB_ROOT_NODE.lock().unwrap()).push(leaf);
    let mut ni: i64 = node_index(leaf);
    (*TAB_ACTIVE_PANE.lock().unwrap()).push((*NODE_PANE.lock().unwrap())[(ni) as usize].clone());
    (*TAB_ZOOMED_PANE.lock().unwrap()).push(0);
    { let __a2r_gv = tab; *WS_ACTIVE_TAB.lock().unwrap() = __a2r_gv; };
    bump_layout_epoch();
    return tab;
}

pub fn mux_close_tab(tab_id: i64) -> i64 {
    let mut ti: i64 = tab_index(tab_id);
    if ti < 0 {
        return -1;
    }
    if ((*TAB_IDS.lock().unwrap()).len() as i64) == 1 {
        return 0;
    }

    let mut i: i64 = ((*PANE_IDS.lock().unwrap()).len() as i64) - 1;
    loop {
        if i < 0 {
            break;
        }
        if (*PANE_TAB_IDS.lock().unwrap())[(i) as usize].clone() == tab_id {
            let mut h: i64 = (*PANE_HANDLES.lock().unwrap())[(i) as usize].clone();
            engine_free(h);
            remove_pane_at(i);
        }
        i = i - 1;
    }

    i = ((*NODE_IDS.lock().unwrap()).len() as i64) - 1;
    loop {
        if i < 0 {
            break;
        }
        if (*NODE_TAB_IDS.lock().unwrap())[(i) as usize].clone() == tab_id {
            { let __a2r_gv = list_remove_int((*NODE_IDS.lock().unwrap()).clone(), i); *NODE_IDS.lock().unwrap() = __a2r_gv; };
            { let __a2r_gv = list_remove_int((*NODE_TAB_IDS.lock().unwrap()).clone(), i); *NODE_TAB_IDS.lock().unwrap() = __a2r_gv; };
            { let __a2r_gv = list_remove_int((*NODE_AXIS.lock().unwrap()).clone(), i); *NODE_AXIS.lock().unwrap() = __a2r_gv; };
            { let __a2r_gv = list_remove_int((*NODE_RATIO.lock().unwrap()).clone(), i); *NODE_RATIO.lock().unwrap() = __a2r_gv; };
            { let __a2r_gv = list_remove_int((*NODE_FIRST.lock().unwrap()).clone(), i); *NODE_FIRST.lock().unwrap() = __a2r_gv; };
            { let __a2r_gv = list_remove_int((*NODE_SECOND.lock().unwrap()).clone(), i); *NODE_SECOND.lock().unwrap() = __a2r_gv; };
            { let __a2r_gv = list_remove_int((*NODE_PANE.lock().unwrap()).clone(), i); *NODE_PANE.lock().unwrap() = __a2r_gv; };
        }
        i = i - 1;
    }
    { let __a2r_gv = list_remove_int((*TAB_IDS.lock().unwrap()).clone(), ti); *TAB_IDS.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = list_remove_int((*TAB_ROOT_NODE.lock().unwrap()).clone(), ti); *TAB_ROOT_NODE.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = list_remove_int((*TAB_ACTIVE_PANE.lock().unwrap()).clone(), ti); *TAB_ACTIVE_PANE.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = list_remove_int((*TAB_ZOOMED_PANE.lock().unwrap()).clone(), ti); *TAB_ZOOMED_PANE.lock().unwrap() = __a2r_gv; };
    if (*WS_ACTIVE_TAB.lock().unwrap()) == tab_id {
        if ((*TAB_IDS.lock().unwrap()).len() as i64) > 0 {
            { let __a2r_gv = (*TAB_IDS.lock().unwrap())[(0) as usize].clone(); *WS_ACTIVE_TAB.lock().unwrap() = __a2r_gv; };
        } else {
            { let __a2r_gv = 0; *WS_ACTIVE_TAB.lock().unwrap() = __a2r_gv; };
        }
    }
    bump_layout_epoch();
    return 1;
}

pub fn mux_activate_tab(tab_id: i64) -> i64 {
    let mut ti: i64 = tab_index(tab_id);
    if ti < 0 {
        return -1;
    }
    { let __a2r_gv = tab_id; *WS_ACTIVE_TAB.lock().unwrap() = __a2r_gv; };
    bump_layout_epoch();
    return 1;
}

pub fn mux_snapshot() -> String {
    let mut at: i64 = (*WS_ACTIVE_TAB.lock().unwrap());
    let mut out: String = format!("{}{}", "{\"workspace\":{\"active_tab\":", at.to_string());
    out = format!("{}{}", out, "},\"tabs\":[");
    let mut i: i64 = 0;
    let mut n: i64 = ((*TAB_IDS.lock().unwrap()).len() as i64);
    loop {
        if i >= n {
            break;
        }
        if i > 0 {
            out = format!("{}{}", out, ",");
        }
        out = format!("{}{}", format!("{}{}", out, "{\"id\":"), (*TAB_IDS.lock().unwrap())[(i) as usize].clone().to_string());
        out = format!("{}{}", format!("{}{}", out, ",\"root\":"), (*TAB_ROOT_NODE.lock().unwrap())[(i) as usize].clone().to_string());
        out = format!("{}{}", format!("{}{}", out, ",\"active_pane\":"), (*TAB_ACTIVE_PANE.lock().unwrap())[(i) as usize].clone().to_string());
        out = format!("{}{}", format!("{}{}", format!("{}{}", out, ",\"zoomed_pane\":"), (*TAB_ZOOMED_PANE.lock().unwrap())[(i) as usize].clone().to_string()), "}");
        i = i + 1;
    }
    out = format!("{}{}", out, "],\"nodes\":[");
    i = 0;
    n = ((*NODE_IDS.lock().unwrap()).len() as i64);
    loop {
        if i >= n {
            break;
        }
        if i > 0 {
            out = format!("{}{}", out, ",");
        }
        out = format!("{}{}", format!("{}{}", out, "{\"id\":"), (*NODE_IDS.lock().unwrap())[(i) as usize].clone().to_string());
        out = format!("{}{}", format!("{}{}", out, ",\"tab\":"), (*NODE_TAB_IDS.lock().unwrap())[(i) as usize].clone().to_string());
        out = format!("{}{}", format!("{}{}", out, ",\"axis\":"), (*NODE_AXIS.lock().unwrap())[(i) as usize].clone().to_string());
        out = format!("{}{}", format!("{}{}", out, ",\"ratio\":"), (*NODE_RATIO.lock().unwrap())[(i) as usize].clone().to_string());
        out = format!("{}{}", format!("{}{}", out, ",\"first\":"), (*NODE_FIRST.lock().unwrap())[(i) as usize].clone().to_string());
        out = format!("{}{}", format!("{}{}", out, ",\"second\":"), (*NODE_SECOND.lock().unwrap())[(i) as usize].clone().to_string());
        out = format!("{}{}", format!("{}{}", format!("{}{}", out, ",\"pane\":"), (*NODE_PANE.lock().unwrap())[(i) as usize].clone().to_string()), "}");
        i = i + 1;
    }
    out = format!("{}{}", out, "],\"panes\":[");
    i = 0;
    n = ((*PANE_IDS.lock().unwrap()).len() as i64);
    loop {
        if i >= n {
            break;
        }
        if i > 0 {
            out = format!("{}{}", out, ",");
        }
        out = format!("{}{}", format!("{}{}", out, "{\"id\":"), (*PANE_IDS.lock().unwrap())[(i) as usize].clone().to_string());
        out = format!("{}{}", format!("{}{}", out, ",\"handle\":"), (*PANE_HANDLES.lock().unwrap())[(i) as usize].clone().to_string());
        out = format!("{}{}", format!("{}{}", format!("{}{}", out, ",\"key\":\""), (*PANE_KEYS.lock().unwrap())[(i) as usize].clone()), "\"");
        out = format!("{}{}", format!("{}{}", out, ",\"tab\":"), (*PANE_TAB_IDS.lock().unwrap())[(i) as usize].clone().to_string());
        out = format!("{}{}", out, ",\"exited\":");
        if (*PANE_EXITED.lock().unwrap())[(i) as usize].clone() {
            out = format!("{}{}", out, "true");
        } else {
            out = format!("{}{}", out, "false");
        }

        out = format!("{}{}", out, "}");
        i = i + 1;
    }
    out = format!("{}{}", format!("{}{}", out, "],\"focus\":{\"pane\":"), mux_focus_pane_id().to_string());
    out = format!("{}{}", format!("{}{}", format!("{}{}", out, ",\"handle\":"), mux_focus_handle().to_string()), "}}");
    return out;
}

pub fn get_lines() -> Vec<String> {
    mux_init();
    mux_drain_actions();
    let mut handle: i64 = mux_focus_handle();
    if handle == 0 {
        let mut empty: Vec<String> = vec![];
        return empty;
    }
    drain_invisible();
    let mut focus_pid: i64 = mux_focus_pane_id();
    let mut vis: Vec<i64> = mux_visible_pane_ids();
    let mut focus_snapshot: Vec<String> = vec![];
    let mut i: i64 = 0;
    let mut n: i64 = (vis.len() as i64);
    loop {
        if i >= n {
            break;
        }
        let mut pid: i64 = vis[(i) as usize].clone();
        let mut pi: i64 = pane_index(pid);
        if pi >= 0 {
            let mut h: i64 = (*PANE_HANDLES.lock().unwrap())[(pi) as usize].clone();
            let mut key: String = (*PANE_KEYS.lock().unwrap())[(pi) as usize].clone();
            let mut applied: i64 = engine_apply_resize_for(h, key.as_str());
            if applied > 0 {
                (*PANE_COLS.lock().unwrap())[(pi) as usize] = engine_viewport_cols(h);
                (*PANE_ROWS.lock().unwrap())[(pi) as usize] = engine_viewport_rows(h);
                if pid == focus_pid {
                    { let __a2r_gv = engine_viewport_cols(h); *COLS.lock().unwrap() = __a2r_gv; };
                    { let __a2r_gv = engine_viewport_rows(h); *ROWS.lock().unwrap() = __a2r_gv; };
                }            }            let mut snap: Vec<String> = engine_rows_for(h, key.as_str());
            if pid == focus_pid {
                focus_snapshot = snap.clone();
            }        }
        i = i + 1;
    }


    if (*BOOTED.lock().unwrap()) == false {
        let mut tries: i64 = 0;
        loop {
            if tries >= 400 {
                break;
            }
            if (focus_snapshot.len() as i64) > 0 {
                break;
            }
            focus_snapshot = engine_rows_for(handle, mux_focus_key_inner().as_str());
            tries = tries + 1;
        }
        { let __a2r_gv = true; *BOOTED.lock().unwrap() = __a2r_gv; };
    }
    { let __a2r_gv = engine_is_exited(handle); *EXITED.lock().unwrap() = __a2r_gv; };
    return focus_snapshot;
}

/// 分屏:焦点 Pane 的叶位替换为分支(原叶 first、新 Pane second;
/// axis 0=纵向 1=横向;比例 500‰)。返回新 Pane id(0 = 失败;-2 =
/// 超过 MAX_PANES 槽位帽)。深度不限(PLAN-020:矩形投影消费)。
/// 关 Pane:兄弟收编父位(wezterm remove_pane/kitty collapse 同语义);
/// 被关者引擎柄 free(所有权铁律);关的是焦点 → 焦点落兄弟子树最左叶。
/// 关末 Pane = 关其 Tab(PLAN-019 D1,018 §10.4 裁定承接);关的是
/// 末 Tab → mux_close_tab 内拒绝(0,app 常驻)。
/// 1 = 已关(含转关 Tab);0 = 末 Tab 拒绝;-1 = 未找到。
/// 焦点切换(1 = 成功;-1 = 未找到)。
/// 缩放开关(活动 Tab;zoomed_pane 0=无)。返回缩放中 1 / 取消 0。
/// 调比例(PLAN-020 D5 键盘兼容面):pane 所在叶的父分支比例,经
/// mux_resize_branch 同一落定段(钳位 + 磁吸;G6 同一比例真相源)。
/// 返回落定比例(负 = 未找到/无父分支)。
/// 新 Tab(单 Pane;自动激活;profile 名 "" = default_profile,未命中
/// 回落缺省 shell)。返回 tab id(0 = spawn 失败)。
/// 关 Tab:该 tab 全部 Pane 引擎柄 free、pane/节点/表行全量摘除。
/// 1 = 已关;0 = 末 Tab 拒绝;-1 = 未找到。
/// 激活 Tab(1/-1)。
/// 结构快照(JSON 串;/api/mux/snapshot 断言面)。
/// 每拍驱动(首调 mux_init:单 Workspace + 初始 Tab/Pane spawn)。
/// 泵三档(PLAN-019 D1):焦点 Pane = 定向几何泵 + 定向快照(旁路投喂
/// pane key 槽)+ 键入泵目标;可见非焦点 Pane = 同等全量投喂(各自 pane
/// key,分屏后画面不冻结);不可见 Pane(zoom 掩盖/他 Tab)= drain-only
/// (收割引擎防 014 积压,不投喂 widget)。返回焦点 Pane 快照
/// (焦点门面:vue/tick 消费面零变)。
/// 不可见 Pane drain-only:收割引擎输出(快照刷新)不投喂任何 widget
/// (key "-hidden-" 不命中注册表;014 积压护栏维持)。
fn drain_invisible() -> i64 {
    let mut vis: Vec<i64> = mux_visible_pane_ids();
    let mut i: i64 = 0;
    let mut n: i64 = ((*PANE_IDS.lock().unwrap()).len() as i64);
    loop {
        if i >= n {
            break;
        }
        let mut pid: i64 = (*PANE_IDS.lock().unwrap())[(i) as usize].clone();
        if contains_int(vis.clone(), pid) == false {
            let mut h: i64 = (*PANE_HANDLES.lock().unwrap())[(i) as usize].clone();
            let mut sink: Vec<String> = engine_rows_for(h, "-hidden-");
            let mut keep: i64 = (sink.len() as i64);
            if keep > 0 {
                keep = 1;
            }        }
        i = i + 1;
    }
    return 0;
}

pub fn term_send(line: &str) {
    let mut handle: i64 = mux_focus_handle();
    engine_write_line(handle, line);
}

pub fn term_interrupt() -> i64 {
    let mut handle: i64 = mux_focus_handle();
    return engine_interrupt(handle);
}

pub fn term_menu_take() -> i64 {
    return engine_menu_take();
}

pub fn term_pump_input() -> i64 {
    let mut vis: Vec<i64> = mux_visible_pane_ids();
    let mut total: i64 = 0;
    let mut i: i64 = 0;
    let mut n: i64 = (vis.len() as i64);
    loop {
        if i >= n {
            break;
        }
        let mut pid: i64 = vis[(i) as usize].clone();
        let mut pi: i64 = pane_index(pid);
        if pi >= 0 {
            let mut h: i64 = (*PANE_HANDLES.lock().unwrap())[(pi) as usize].clone();
            let mut key: String = (*PANE_KEYS.lock().unwrap())[(pi) as usize].clone();
            let mut pumped: i64 = engine_pump_for(h, key.as_str());
            if pumped > 0 {
                total = total + pumped;
                set_focus_if_active_tab(pid);
            }        }
        i = i + 1;
    }
    return total;
}

/// 宿主 → 子进程一行输入(胶水侧补 \r\n;焦点 Pane 门面)。
/// Ctrl+C 中断(Break→C 双发语义,引擎契约 003 §4.1;焦点 Pane)。
/// 菜单动作载荷取走(PLAN-015 D4;on_menu 消息后由 .Menu 处理器消费):
/// 0=Copy 1=Paste 2=SelectAll 3=Interrupt;-1=无载荷(读取即取走)。
/// 载荷 3 → term_interrupt()(显式中断,不误伤 idle ash;0/1/2 暂忽略)。
/// 直键入泵(PLAN-019 D1 键入路由):逐可见 Pane 排空各自 queue 裸写
/// 各自引擎(无 \r\n 补缀;Enter 已是 VT 串里的 \r)——键入恒落用户
/// 点击聚焦的那个 terminal 槽,Pane 间零串线。本次有泵出的 Pane 记为
/// 其 Tab 焦点(打字随动焦点;V1 近似:纯点击不打字不迁移焦点)。
/// 返回泵送键数。
/// 打字随动焦点:pid 记为其 Tab 焦点(仅当该 Tab = 当前活动 Tab;
/// 不可见 Pane 队列无键,本函数只被可见泵面调用)。
fn set_focus_if_active_tab(pid: i64) -> i64 {
    let mut ti: i64 = active_tab_index();
    if ti < 0 {
        return 0;
    }
    let mut pi: i64 = pane_index(pid);
    if pi >= 0 {
        if (*PANE_TAB_IDS.lock().unwrap())[(pi) as usize].clone() == (*WS_ACTIVE_TAB.lock().unwrap()) {
            (*TAB_ACTIVE_PANE.lock().unwrap())[(ti) as usize] = pid;
        }    }
    return 1;
}

pub fn term_apply_resize() -> i64 {
    let mut pid: i64 = mux_focus_pane_id();
    if pid == 0 {
        return 0;
    }
    let mut pi: i64 = pane_index(pid);
    if pi < 0 {
        return 0;
    }
    let mut key: String = (*PANE_KEYS.lock().unwrap())[(pi) as usize].clone();
    let mut h: i64 = (*PANE_HANDLES.lock().unwrap())[(pi) as usize].clone();
    let mut applied: i64 = engine_apply_resize_for(h, key.as_str());
    if applied > 0 {
        (*PANE_COLS.lock().unwrap())[(pi) as usize] = engine_viewport_cols(h);
        (*PANE_ROWS.lock().unwrap())[(pi) as usize] = engine_viewport_rows(h);
        { let __a2r_gv = engine_viewport_cols(h); *COLS.lock().unwrap() = __a2r_gv; };
        { let __a2r_gv = engine_viewport_rows(h); *ROWS.lock().unwrap() = __a2r_gv; };
    }
    return applied;
}

pub fn term_cols() -> i64 {
    return (*COLS.lock().unwrap());
}

pub fn term_rows() -> i64 {
    return (*ROWS.lock().unwrap());
}

pub fn term_cursor_row() -> i64 {
    let mut handle: i64 = mux_focus_handle();
    if handle == 0 {
        return 0;
    }
    return engine_cursor_row(handle);
}

pub fn term_cursor_col() -> i64 {
    let mut handle: i64 = mux_focus_handle();
    if handle == 0 {
        return 0;
    }
    return engine_cursor_col(handle);
}

pub fn term_backlog_sample() -> i64 {
    let mut handle: i64 = mux_focus_handle();
    if handle == 0 {
        return 0;
    }
    let mut fresh: i64 = engine_backlog_take_alerts(handle);
    { let __a2r_gv = (*BL_ALERTS_TOTAL.lock().unwrap()) + fresh; *BL_ALERTS_TOTAL.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = engine_backlog_pending_mb(handle); *BL_PENDING_MB.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = engine_backlog_paused(handle); *BL_PAUSED.lock().unwrap() = __a2r_gv; };
    { let __a2r_gv = engine_backlog_dropped(handle); *BL_DROPPED.lock().unwrap() = __a2r_gv; };
    return fresh;
}

pub fn term_backlog_alerts_total() -> i64 {
    return (*BL_ALERTS_TOTAL.lock().unwrap());
}

pub fn term_backlog_pending_mb() -> i64 {
    return (*BL_PENDING_MB.lock().unwrap());
}

pub fn term_backlog_paused() -> i64 {
    return (*BL_PAUSED.lock().unwrap());
}

pub fn term_backlog_dropped() -> i64 {
    return (*BL_DROPPED.lock().unwrap());
}

pub fn term_exited() -> bool {
    return (*EXITED.lock().unwrap());
}

pub fn mux_cols() -> i64 {
    return (*COLS.lock().unwrap());
}

pub fn mux_rows() -> i64 {
    return (*ROWS.lock().unwrap());
}

pub fn mux_focus_key() -> String {
    return mux_focus_key_inner();
}

pub fn mux_focus_id() -> i64 {
    return mux_focus_pane_id();
}

static TICK_COUNTER: Mutex<i64> = Mutex::new(0);

static LAST_FULL_TICK: Mutex<i64> = Mutex::new(0);

pub fn term_scroll_pending() -> i64 {
    let mut vis: Vec<i64> = mux_visible_pane_ids();
    let mut i: i64 = 0;
    let mut n: i64 = (vis.len() as i64);
    loop {
        if i >= n {
            break;
        }
        let mut pi: i64 = pane_index(vis[(i) as usize].clone());
        if pi >= 0 {
            if engine_scroll_pending_for((*PANE_HANDLES.lock().unwrap())[(pi) as usize].clone(), (*PANE_KEYS.lock().unwrap())[(pi) as usize].clone()) != 0 {
                return 1;
            }        }
        i = i + 1;
    }
    return 0;
}

pub fn tick_gate() -> i64 {
    { let __a2r_gv = (*TICK_COUNTER.lock().unwrap()) + 1; *TICK_COUNTER.lock().unwrap() = __a2r_gv; };
    if (*TICK_COUNTER.lock().unwrap()) - (*LAST_FULL_TICK.lock().unwrap()) >= 3 {
        { let __a2r_gv = (*TICK_COUNTER.lock().unwrap()); *LAST_FULL_TICK.lock().unwrap() = __a2r_gv; };
        return 1;
    }
    if term_scroll_pending() == 1 {
        { let __a2r_gv = (*TICK_COUNTER.lock().unwrap()); *LAST_FULL_TICK.lock().unwrap() = __a2r_gv; };
        return 1;
    }
    return 0;
}

pub fn term_profile_names() -> Vec<String> {
    return config_profiles();
}

pub fn term_profiles() -> Vec<String> {
    return config_profiles_full();
}

pub fn mux_tabs() -> Vec<String> {
    let mut out: Vec<String> = vec![];
    let mut i: i64 = 0;
    let mut n: i64 = ((*TAB_IDS.lock().unwrap()).len() as i64);
    loop {
        if i >= n {
            break;
        }
        let mut rec: String = format!("{}{}", (*TAB_IDS.lock().unwrap())[(i) as usize].clone().to_string(), "|");
        if (*TAB_IDS.lock().unwrap())[(i) as usize].clone() == (*WS_ACTIVE_TAB.lock().unwrap()) {
            rec = format!("{}{}", rec, "1|");
        } else {
            rec = format!("{}{}", rec, "0|");
        }

        rec = format!("{}{}", rec, mux_tab_title_at(i));
        out.push(rec.to_string());
        i = i + 1;
    }
    return out;
}

pub fn mux_tab_count() -> i64 {
    return ((*TAB_IDS.lock().unwrap()).len() as i64);
}

pub fn mux_tab_id_at(i: i64) -> i64 {
    if i < 0 {
        return 0;
    }
    if i >= (*TAB_IDS.lock().unwrap()).len() as i64 {
        return 0;
    }
    return (*TAB_IDS.lock().unwrap())[(i) as usize].clone();
}

pub fn mux_tab_is_active_at(i: i64) -> i64 {
    if mux_tab_id_at(i) == 0 {
        return 0;
    }
    if (*TAB_IDS.lock().unwrap())[(i) as usize].clone() == (*WS_ACTIVE_TAB.lock().unwrap()) {
        return 1;
    }
    return 0;
}

pub fn mux_tab_title_at(i: i64) -> String {
    let mut n: i64 = i + 1;
    return format!("{}{}", "shell ", n.to_string());
}

pub fn mux_pane_lines(pane_id: i64) -> Vec<String> {
    let mut pi: i64 = pane_index(pane_id);
    if pi < 0 {
        let mut empty: Vec<String> = vec![];
        return empty;
    }
    let mut h: i64 = (*PANE_HANDLES.lock().unwrap())[(pi) as usize].clone();
    let mut key: String = (*PANE_KEYS.lock().unwrap())[(pi) as usize].clone();
    return engine_rows_for(h, key.as_str());
}

pub fn mux_pane_cols(pane_id: i64) -> i64 {
    let mut pi: i64 = pane_index(pane_id);
    if pi < 0 {
        return 100;
    }
    return (*PANE_COLS.lock().unwrap())[(pi) as usize].clone();
}

pub fn mux_pane_rows(pane_id: i64) -> i64 {
    let mut pi: i64 = pane_index(pane_id);
    if pi < 0 {
        return 30;
    }
    return (*PANE_ROWS.lock().unwrap())[(pi) as usize].clone();
}

pub fn mux_pane_cursor_row(pane_id: i64) -> i64 {
    let mut pi: i64 = pane_index(pane_id);
    if pi < 0 {
        return 0;
    }
    return engine_cursor_row((*PANE_HANDLES.lock().unwrap())[(pi) as usize].clone());
}

pub fn mux_pane_cursor_col(pane_id: i64) -> i64 {
    let mut pi: i64 = pane_index(pane_id);
    if pi < 0 {
        return 0;
    }
    return engine_cursor_col((*PANE_HANDLES.lock().unwrap())[(pi) as usize].clone());
}

pub fn mux_visible_pane_count() -> i64 {
    return (mux_visible_pane_ids().len() as i64);
}

pub fn mux_split_axis() -> i64 {
    let mut ti: i64 = active_tab_index();
    if ti < 0 {
        return -1;
    }
    let mut root: i64 = (*TAB_ROOT_NODE.lock().unwrap())[(ti) as usize].clone();
    let mut ri: i64 = node_index(root);
    if ri < 0 {
        return -1;
    }
    if (*NODE_PANE.lock().unwrap())[(ri) as usize].clone() != 0 {
        return -1;
    }
    return (*NODE_AXIS.lock().unwrap())[(ri) as usize].clone();
}

pub fn mux_slot_pane_id(slot: i64) -> i64 {
    rects_ready();
    let mut k: i64 = slot;
    if k < 1 {
        k = 1;
    }
    if k > (*MAX_PANES.lock().unwrap()) {
        return 0;
    }
    if mux_rect_kind(k) == 1 {
        return (*RECT_PANE.lock().unwrap())[(k - 1) as usize].clone();
    }
    return 0;
}

pub fn mux_slot_pane_key(slot: i64) -> String {
    rects_ready();
    let mut k: i64 = slot;
    if k < 1 {
        k = 1;
    }
    if k > (*MAX_PANES.lock().unwrap()) {
        return "".to_string();
    }
    if mux_rect_kind(k) == 1 {
        return (*RECT_KEY.lock().unwrap())[(k - 1) as usize].clone();
    }
    return "".to_string();
}

pub fn mux_zoom_active() -> i64 {
    let mut ti: i64 = active_tab_index();
    if ti < 0 {
        return 0;
    }
    if (*TAB_ZOOMED_PANE.lock().unwrap())[(ti) as usize].clone() != 0 {
        return 1;
    }
    return 0;
}

pub fn mux_layout() -> String {
    let mut ti: i64 = active_tab_index();
    if ti < 0 {
        return "{\"tab\":0,\"axis\":-1,\"slots\":[0,0],\"zoom\":0,\"visible\":0,\"focus\":0,\"rects\":[],\"dividers\":[]}".to_string();
    }
    let mut zoomed: i64 = (*TAB_ZOOMED_PANE.lock().unwrap())[(ti) as usize].clone();
    rects_ready();
    let mut out: String = format!("{}{}", "{\"tab\":", (*TAB_IDS.lock().unwrap())[(ti) as usize].clone().to_string());
    out = format!("{}{}", format!("{}{}", out, ",\"axis\":"), mux_split_axis().to_string());
    out = format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", format!("{}{}", out, ",\"slots\":["), mux_slot_pane_id(1).to_string()), ","), mux_slot_pane_id(2).to_string()), "]");
    out = format!("{}{}", out, ",\"zoom\":");
    if zoomed != 0 {
        out = format!("{}{}", out, zoomed.to_string());
    } else {
        out = format!("{}{}", out, "0");
    }

    out = format!("{}{}", format!("{}{}", out, ",\"visible\":"), mux_visible_pane_count().to_string());
    out = format!("{}{}", format!("{}{}", out, ",\"focus\":"), mux_focus_pane_id().to_string());

    out = format!("{}{}", out, ",\"rects\":[");
    let mut i: i64 = 0;
    let mut n: i64 = ((*RECT_KIND.lock().unwrap()).len() as i64);
    let mut first: i64 = 1;
    loop {
        if i >= n {
            break;
        }
        if (*RECT_KIND.lock().unwrap())[(i) as usize].clone() == 1 {
            if first == 1 {
                first = 0;
            } else {
                out = format!("{}{}", out, ",");
            }
            out = format!("{}{}", format!("{}{}", out, "{\"pane\":"), (*RECT_PANE.lock().unwrap())[(i) as usize].clone().to_string());
            out = format!("{}{}", format!("{}{}", out, ",\"x\":"), (*RECT_X.lock().unwrap())[(i) as usize].clone().to_string());
            out = format!("{}{}", format!("{}{}", out, ",\"y\":"), (*RECT_Y.lock().unwrap())[(i) as usize].clone().to_string());
            out = format!("{}{}", format!("{}{}", out, ",\"w\":"), (*RECT_W.lock().unwrap())[(i) as usize].clone().to_string());
            out = format!("{}{}", format!("{}{}", format!("{}{}", out, ",\"h\":"), (*RECT_H.lock().unwrap())[(i) as usize].clone().to_string()), "}");
        }
        i = i + 1;
    }
    out = format!("{}{}", out, "]");

    out = format!("{}{}", out, ",\"dividers\":[");
    i = 0;
    first = 1;
    loop {
        if i >= n {
            break;
        }
        if (*RECT_KIND.lock().unwrap())[(i) as usize].clone() == 2 {
            if first == 1 {
                first = 0;
            } else {
                out = format!("{}{}", out, ",");
            }
            out = format!("{}{}", format!("{}{}", out, "{\"branch\":"), (*RECT_BRANCH.lock().unwrap())[(i) as usize].clone().to_string());
            out = format!("{}{}", format!("{}{}", out, ",\"axis\":"), (*RECT_AXIS.lock().unwrap())[(i) as usize].clone().to_string());
            out = format!("{}{}", format!("{}{}", out, ",\"x\":"), (*RECT_X.lock().unwrap())[(i) as usize].clone().to_string());
            out = format!("{}{}", format!("{}{}", out, ",\"y\":"), (*RECT_Y.lock().unwrap())[(i) as usize].clone().to_string());
            out = format!("{}{}", format!("{}{}", out, ",\"w\":"), (*RECT_W.lock().unwrap())[(i) as usize].clone().to_string());
            out = format!("{}{}", format!("{}{}", format!("{}{}", out, ",\"h\":"), (*RECT_H.lock().unwrap())[(i) as usize].clone().to_string()), "}");
        }
        i = i + 1;
    }
    out = format!("{}{}", out, "]}");
    return out;
}
