// Auto-generated by a2r transpiler

use crate::engine::{engine_spawn, engine_write_line, engine_rows, engine_resize, engine_interrupt, engine_is_exited, engine_free};
#[derive(Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
enum AppMsg {
    EngineTick,
    SendLine(String),
    Resized(i64, i64),
    Interrupted,
}


#[derive(Clone, Debug)]
pub struct TermApp {
    pub handle: i64,
    pub cols: i64,
    pub rows: i64,
    pub lines: Vec<String>,
    pub exited: bool,
}

impl TermApp {
    pub fn new(cols: i64, rows: i64) -> TermApp {
        let h = engine_spawn(cols, rows);
        return TermApp { handle: h, cols: cols, rows: rows, lines: vec![], exited: false };
    }
    pub fn tick(&mut self) {
        self.lines = engine_rows(self.handle.clone());
        self.exited = engine_is_exited(self.handle.clone());
    }
    pub fn send_line(&mut self, line: &str) {
        engine_write_line(self.handle.clone(), line);
    }
    pub fn resize(&mut self, mut cols: i64, mut rows: i64) {
        engine_resize(self.handle.clone(), cols, rows);
        self.cols = cols;
        self.rows = rows;
    }
    pub fn interrupt(&self) {
        engine_interrupt(self.handle.clone());
    }
    pub fn dispose(&self) {
        engine_free(self.handle.clone());
    }
}

/// 每拍驱动:收割引擎输出并拉取视口快照(形态甲 props 数据源;
/// engine_rows 内联 feed+快照)。
/// headless 冒烟(T9 对拍门禁 a2r 侧驱动核):spawn → echo → tick 拉取。
fn main() {
    let mut app = TermApp::new(80, 24);
    app.send_line("echo autoterm_at_ok");
    app.tick();
    println!("at-app ready");
}
