// Auto-generated by a2r transpiler

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
enum Damage {
    Full,
    Lines(Vec<i64>),
}


#[derive(Clone, Copy, Debug)]
struct GridSize {
    pub cols: i64,
    pub rows: i64,
}

impl GridSize {
    fn new(cols: i64, rows: i64) -> GridSize {
        return GridSize { cols: cols, rows: rows };
    }
    fn area(&self) -> i64 {
        return self.cols * self.rows;
    }
}

#[derive(Clone, Debug)]
struct TermSession {
    pub size: GridSize,
    pub exited: bool,
    pub damage: Damage,
}

impl TermSession {
    pub fn new(cols: i64, rows: i64) -> TermSession {
        return TermSession { size: GridSize { cols: cols, rows: rows }, exited: false, damage: Damage::Full.clone() };
    }
    pub fn update(&self, dmg: Damage) -> Damage {
        match dmg {
            Damage::Full => return Damage::Full,
            Damage::Lines(lines) => return Damage::Lines(lines),
        };
        return Damage::Full;
    }
    pub fn clear_selection(&self) -> bool {
        return self.exited;
    }
}

fn main() {
    let session = TermSession::new(80, 24);
    let d = session.update(Damage::Full);
    println!("area = {}", GridSize { cols: 80, rows: 24 }.area());
    println!("damage: {:?}", d);
}
